import express, {Application} from 'express';
import cors from 'cors';
import bodyParser from 'body-parser';
import countryRoutes from './countryRoutes';
const app: Application = express();
const port = process.env.PORT || 3000;
app.use(bodyParser.json());
app.use(express.json());
app.use(function(err:any, req:any, res:any, next:any) {console.log(err);});
app.use(cors());
app.listen(port, () => {console.log(`Server listening on port ${port}`);});
app.use('/v1/', countryRoutes);